/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrardashboard;

import account.accdetails;

import config.Session;
import config.dbconnect;
import ESTRERA.loginform;
import java.awt.Color;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

import reports.report;
import reportss.rreport;

/**
 *
 * @author acer
 */
public class usermaindash extends javax.swing.JFrame {

    /**
     * Creates new form usermaindash
     */
    public usermaindash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        myaccount = new javax.swing.JLabel();
        reports = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        accname = new javax.swing.JLabel();
        application = new javax.swing.JLabel();
        editaccc = new javax.swing.JLabel();
        reports1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(102, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 25));

        minimize.setBackground(new java.awt.Color(102, 255, 204));
        minimize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        main.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 25));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     REGISTERS DASHBOARD");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jLabel1.setOpaque(true);
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 800, 40));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 41, -1, -1));

        myaccount.setBackground(new java.awt.Color(0, 153, 153));
        myaccount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        myaccount.setForeground(new java.awt.Color(0, 204, 204));
        myaccount.setText("  My account");
        myaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myaccountMouseExited(evt);
            }
        });
        sidebar.add(myaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 40));

        reports.setBackground(new java.awt.Color(204, 0, 0));
        reports.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reports.setForeground(new java.awt.Color(0, 204, 204));
        reports.setText("  Reports");
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        sidebar.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 204, 204));
        logout.setText("  Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 130, 40));

        accname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-circle-icon (1).png"))); // NOI18N
        sidebar.add(accname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        application.setBackground(new java.awt.Color(204, 0, 0));
        application.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        application.setForeground(new java.awt.Color(0, 204, 204));
        application.setText("  Applications");
        application.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applicationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applicationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applicationMouseExited(evt);
            }
        });
        sidebar.add(application, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 40));

        editaccc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editaccc.setForeground(new java.awt.Color(0, 204, 204));
        editaccc.setText("  Settings");
        editaccc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editacccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editacccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editacccMouseExited(evt);
            }
        });
        sidebar.add(editaccc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 110, 40));

        reports1.setBackground(new java.awt.Color(204, 0, 0));
        reports1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reports1.setForeground(new java.awt.Color(0, 204, 204));
        reports1.setText("Employess");
        reports1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reports1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reports1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reports1MouseExited(evt);
            }
        });
        sidebar.add(reports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 40));

        main.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 170, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Session sess = Session.getInstance();
        dbconnect dbc = new dbconnect();
        String action = "User with ID "+sess.getId()+" logged out";
         dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" + +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");
        System.exit(0);
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited

    }//GEN-LAST:event_jLabel5MouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered

    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited

    }//GEN-LAST:event_minimizeMouseExited

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
      // current button
reports.setOpaque(true);
reports.setBackground(new java.awt.Color(0, 153, 153));
reports.setForeground(Color.WHITE);

// other buttons
myaccount.setBackground(Color.WHITE);
myaccount.setForeground(new java.awt.Color(0, 153, 153));
myaccount.setOpaque(false);

application.setBackground(Color.WHITE);
application.setForeground(new java.awt.Color(0, 153, 153));
application.setOpaque(false);

editaccc.setBackground(Color.WHITE);
editaccc.setForeground(new java.awt.Color(0, 153, 153));
editaccc.setOpaque(false);

// load content
jDesktopPane1.removeAll();
rreport rp = new rreport();
jDesktopPane1.add(rp).setVisible(true);

    }//GEN-LAST:event_reportsMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
        
    }//GEN-LAST:event_reportsMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Session sess = Session.getInstance();
        dbconnect dbc = new dbconnect();
        String action = "User with ID "+sess.getId()+" logged out";
         dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" + +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");
        System.exit(0);
        loginform lfm = new loginform();
        lfm.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        
    }//GEN-LAST:event_logoutMouseExited

    private void editacccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseClicked
        userditop eo = new userditop();
        eo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editacccMouseClicked

    private void editacccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseEntered
        
    }//GEN-LAST:event_editacccMouseEntered

    private void editacccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseExited
        
    }//GEN-LAST:event_editacccMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
myaccount.setOpaque(true);
myaccount.setBackground(new java.awt.Color(0, 128, 128)); // Teal color
myaccount.setForeground(Color.white);

        
        jDesktopPane1.removeAll();
     accdetails ad = new accdetails();
     jDesktopPane1.add(ad).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        loginform lfm = new loginform();
        lfm.setVisible(true);
        this.dispose();
        }else{
        accname.setText(""+sess.getUsername());}
    }//GEN-LAST:event_formWindowActivated

    private void applicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationMouseClicked
application.setOpaque(true);
application.setBackground(new java.awt.Color(0, 153, 153));
application.setForeground(Color.white);

myaccount.setOpaque(true);
myaccount.setBackground(Color.white);
myaccount.setForeground(new java.awt.Color(0, 128, 128));

reports.setOpaque(true);
reports.setBackground(Color.white);
reports.setForeground(new java.awt.Color(0, 128, 128));

editaccc.setOpaque(true);
editaccc.setBackground(Color.white);
editaccc.setForeground(new java.awt.Color(0, 128, 128));

jDesktopPane1.removeAll();
accdetails ad = new accdetails();
jDesktopPane1.add(ad).setVisible(true);


 
    
    }//GEN-LAST:event_applicationMouseClicked

    private void applicationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationMouseEntered
         
    }//GEN-LAST:event_applicationMouseEntered

    private void applicationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationMouseExited
       
    }//GEN-LAST:event_applicationMouseExited

    private void myaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseExited

    }//GEN-LAST:event_myaccountMouseExited

    private void myaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseEntered

    }//GEN-LAST:event_myaccountMouseEntered

    private void myaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseClicked
  myaccount.setOpaque(true);
 myaccount.setBackground(new java.awt.Color(0, 153, 153));
 myaccount.setForeground(Color.white);



application.setOpaque(true);
application.setBackground(Color.white);
application.setForeground(new java.awt.Color(0, 128, 128));

reports.setBackground(Color.white);
reports.setForeground(new java.awt.Color(0, 128, 128)); // Green color
reports.setOpaque(true);

editaccc.setBackground(Color.white);
editaccc.setForeground(new java.awt.Color(0, 128, 128)); // Green color
editaccc.setOpaque(true);

jDesktopPane1.removeAll();
accdetails ad = new accdetails();
jDesktopPane1.add(ad).setVisible(true);

    }//GEN-LAST:event_myaccountMouseClicked

    private void reports1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseClicked

    private void reports1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseEntered

    private void reports1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usermaindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usermaindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usermaindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usermaindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usermaindash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accname;
    private javax.swing.JLabel application;
    private javax.swing.JLabel editaccc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    public javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel myaccount;
    private javax.swing.JLabel reports;
    private javax.swing.JLabel reports1;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
