/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrardashboard;

import account.editmyaccount;
import account.editpass;
import account.forgotpass;
import config.Session;
import config.dbconnect;
import ESTRERA.loginform;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;

/**
 *
 * @author acer
 */
public class userditop extends javax.swing.JFrame {

    /**
     * Creates new form userditop
     */
    public userditop() {
        initComponents();
    }
  public boolean duplicatecheck(){
            dbconnect dbc = new dbconnect();
            Session sess = Session.getInstance();
            int uid = sess.getId();
            int userid ;

            try{
                String query = "SELECT * FROM recovery WHERE userid = '"+ uid +"'";
                ResultSet resultSet = dbc.getData(query);
                if(resultSet.next()){
                    userid = resultSet.getInt("userid");
                    if(uid == userid){
                        
                    } 

                    return true;
                }
                else{
                    return false;
                }
            } catch (SQLException ex) {
                System.out.println(""+ex);
                return false;
            }

        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        details = new javax.swing.JLabel();
        passwordd = new javax.swing.JLabel();
        recovery = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        goback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(153, 255, 204));
        minimize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        main.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 25));

        jLabel5.setBackground(new java.awt.Color(153, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 25));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 170, 0));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("   MANAGE ACCOUNT INFORMATION:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jLabel1.setOpaque(true);
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 40));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        main.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 970, 480));

        details.setBackground(new java.awt.Color(0, 153, 153));
        details.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        details.setForeground(new java.awt.Color(0, 153, 153));
        details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        details.setText("  Details");
        details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsMouseClicked(evt);
            }
        });
        main.add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        passwordd.setBackground(new java.awt.Color(0, 153, 153));
        passwordd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordd.setForeground(new java.awt.Color(0, 153, 153));
        passwordd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordd.setText("  Password");
        passwordd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passworddMouseClicked(evt);
            }
        });
        main.add(passwordd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, 20));

        recovery.setBackground(new java.awt.Color(0, 153, 153));
        recovery.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        recovery.setForeground(new java.awt.Color(0, 153, 153));
        recovery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recovery.setText("Recovery");
        recovery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recoveryMouseClicked(evt);
            }
        });
        main.add(recovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 120, 20));

        o.setBackground(new java.awt.Color(0, 153, 153));
        o.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        o.setForeground(new java.awt.Color(0, 153, 153));
        o.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o.setText("  Log out");
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oMouseExited(evt);
            }
        });
        main.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 120, 20));

        goback.setBackground(new java.awt.Color(0, 153, 153));
        goback.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        goback.setForeground(new java.awt.Color(0, 153, 153));
        goback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goback.setText("  Go back");
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gobackMouseExited(evt);
            }
        });
        main.add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered

    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited

    }//GEN-LAST:event_minimizeMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Session sess = Session.getInstance();
        dbconnect dbc = new dbconnect();
        String action = "User with ID "+sess.getId()+" logged out";
         dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" + +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited

    }//GEN-LAST:event_jLabel5MouseExited

    private void detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsMouseClicked
        jDesktopPane1.removeAll();
        editmyaccount em = new editmyaccount();
        jDesktopPane1.add(em).setVisible(true);
    }//GEN-LAST:event_detailsMouseClicked

    private void passworddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passworddMouseClicked
        jDesktopPane1.removeAll();
        editpass ep = new editpass();
        jDesktopPane1.add(ep).setVisible(true);
    }//GEN-LAST:event_passworddMouseClicked

    private void recoveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recoveryMouseClicked
        jDesktopPane1.removeAll();
        forgotpass fp = new forgotpass();
        jDesktopPane1.add(fp).setVisible(true);
    }//GEN-LAST:event_recoveryMouseClicked

    private void oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseClicked
        this.dispose();
        Session sess = Session.getInstance();
        dbconnect dbc = new dbconnect();
        String action = "User with ID "+sess.getId()+" logged out";
         dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" + +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");
        System.exit(0);
        loginform lfm = new loginform();
        lfm.setVisible(true);
    }//GEN-LAST:event_oMouseClicked

    private void oMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseEntered
 o.setBackground(Color.WHITE);
o.setForeground(new java.awt.Color(0, 153, 153));
o.setOpaque(true);
;

    }//GEN-LAST:event_oMouseEntered

    private void oMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseExited
       o.setBackground(new java.awt.Color(0, 153, 153));
o.setForeground(Color.WHITE);
o.setOpaque(true);

    }//GEN-LAST:event_oMouseExited

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        this.dispose();
        usermaindash md = new usermaindash();
        md.setVisible(true);

    }//GEN-LAST:event_gobackMouseClicked

    private void gobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseEntered
goback.setBackground(Color.WHITE);
goback.setForeground(new java.awt.Color(0, 153, 153));

    }//GEN-LAST:event_gobackMouseEntered

    private void gobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseExited
     goback.setBackground(new java.awt.Color(0, 153, 153));
goback.setForeground(Color.WHITE);

    }//GEN-LAST:event_gobackMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(duplicatecheck()){
              
         recovery.setVisible(false);
         } else{
         recovery.setVisible(true);
         }       
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         jDesktopPane1.removeAll();
        editmyaccount em = new editmyaccount();
        jDesktopPane1.add(em).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userditop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userditop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userditop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userditop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userditop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel details;
    private javax.swing.JLabel goback;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel o;
    private javax.swing.JLabel passwordd;
    private javax.swing.JLabel recovery;
    // End of variables declaration//GEN-END:variables
}
