/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMINDASH;


import config.Session;
import account.accdetails;

import config.dbconnect;
import User.manageuser;
import ESTRERA.loginform;
import java.awt.Color;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;


import reports.report;


/**
 *
 * @author acer
 */
public class maindash extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public maindash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        myaccount = new javax.swing.JLabel();
        reportss = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        accname = new javax.swing.JLabel();
        editaccc = new javax.swing.JLabel();
        applcation = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(153, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 25));

        minimize.setBackground(new java.awt.Color(153, 255, 204));
        minimize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        main.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 25));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("     ADMINISTRATORS DASHBOARD");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jLabel1.setOpaque(true);
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 810, 70));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 41, -1, -1));

        users.setBackground(new java.awt.Color(221, 21, 21));
        users.setForeground(new java.awt.Color(0, 153, 153));
        users.setText("  Users");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
        });
        sidebar.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 40));

        myaccount.setBackground(new java.awt.Color(255, 255, 255));
        myaccount.setForeground(new java.awt.Color(0, 153, 153));
        myaccount.setText("  My accouunt");
        myaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myaccountMouseExited(evt);
            }
        });
        sidebar.add(myaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 40));

        reportss.setBackground(new java.awt.Color(204, 0, 0));
        reportss.setForeground(new java.awt.Color(0, 153, 153));
        reportss.setText("  Reports");
        reportss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportssMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportssMouseExited(evt);
            }
        });
        sidebar.add(reportss, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 40));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setForeground(new java.awt.Color(0, 153, 153));
        logout.setText("  Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 160, 40));

        accname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/account-circle-icon (1).png"))); // NOI18N
        sidebar.add(accname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        editaccc.setForeground(new java.awt.Color(0, 153, 153));
        editaccc.setText("  Settings");
        editaccc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editacccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editacccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editacccMouseExited(evt);
            }
        });
        sidebar.add(editaccc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 40));

        applcation.setBackground(new java.awt.Color(204, 0, 0));
        applcation.setForeground(new java.awt.Color(0, 153, 153));
        applcation.setText("  Application");
        applcation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applcationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applcationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applcationMouseExited(evt);
            }
        });
        sidebar.add(applcation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 40));

        main.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 170, 610));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        main.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
       
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
         dbconnect dbc = new dbconnect();
         Session sess= Session.getInstance();
         
          String action = "User with ID "+sess.getId()+" logged out";
        dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");
        
        loginform lfm = new loginform();
        lfm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void reportssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportssMouseExited
        
    }//GEN-LAST:event_reportssMouseExited

    private void reportssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportssMouseEntered
        
    }//GEN-LAST:event_reportssMouseEntered

    private void reportssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportssMouseClicked
      // current button
reportss.setOpaque(true);
reportss.setBackground(new java.awt.Color(0, 153, 153));
reportss.setForeground(Color.WHITE);

// other buttons
myaccount.setBackground(Color.WHITE);
myaccount.setForeground(new java.awt.Color(0, 153, 153));
myaccount.setOpaque(false);

users.setBackground(Color.WHITE);
users.setForeground(new java.awt.Color(0, 153, 153));
users.setOpaque(false);

applcation.setBackground(Color.WHITE);
applcation.setForeground(new java.awt.Color(0, 153, 153));
applcation.setOpaque(false);

editaccc.setBackground(Color.WHITE);
editaccc.setForeground(new java.awt.Color(0, 153, 153));
editaccc.setOpaque(false);

// load report panel
report rp = new report();
jDesktopPane1.removeAll();
jDesktopPane1.add(rp).setVisible(true);

    }//GEN-LAST:event_reportssMouseClicked

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited
       
    }//GEN-LAST:event_usersMouseExited

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
        
    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
    // current button
users.setOpaque(true);
users.setBackground(new java.awt.Color(0, 153, 153));
users.setForeground(Color.WHITE);

// other buttons
myaccount.setBackground(Color.WHITE);
myaccount.setForeground(new java.awt.Color(0, 153, 153));
myaccount.setOpaque(false);

applcation.setBackground(Color.WHITE);
applcation.setForeground(new java.awt.Color(0, 153, 153));
applcation.setOpaque(false);

reportss.setBackground(Color.WHITE);
reportss.setForeground(new java.awt.Color(0, 153, 153));
reportss.setOpaque(false);

editaccc.setBackground(Color.WHITE);
editaccc.setForeground(new java.awt.Color(0, 153, 153));
editaccc.setOpaque(false);
  
        
        
        jDesktopPane1.removeAll();
     manageuser mu = new manageuser();
       jDesktopPane1.add(mu).setVisible(true);
    }//GEN-LAST:event_usersMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        loginform lfm = new loginform();
        lfm.setVisible(true);
        this.dispose();
        }else{
        accname.setText(""+sess.getUsername());}
        
      
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Session sess = Session.getInstance();
        dbconnect dbc = new dbconnect();
        String action = "User with ID "+sess.getId()+" logged out";
         dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" + +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");
        
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        
    }//GEN-LAST:event_jLabel5MouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        
    }//GEN-LAST:event_minimizeMouseExited

    private void editacccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseClicked
        editoption eo = new editoption();
        eo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editacccMouseClicked

    private void editacccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseEntered
       
    }//GEN-LAST:event_editacccMouseEntered

    private void editacccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseExited
        
    }//GEN-LAST:event_editacccMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 myaccount.setOpaque(true);
myaccount.setBackground(new java.awt.Color(0, 153, 153));
myaccount.setForeground(Color.WHITE);

jDesktopPane1.removeAll();
accdetails ad = new accdetails();
jDesktopPane1.add(ad).setVisible(true);

    }//GEN-LAST:event_formWindowOpened

    private void applcationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applcationMouseClicked
   // current button
applcation.setOpaque(true);
applcation.setBackground(new java.awt.Color(0, 153, 153));
applcation.setForeground(Color.WHITE);

// other buttons
users.setBackground(Color.WHITE);
users.setForeground(new java.awt.Color(0, 153, 153));
users.setOpaque(false);

myaccount.setBackground(Color.WHITE);
myaccount.setForeground(new java.awt.Color(0, 153, 153));
myaccount.setOpaque(false);

reportss.setBackground(Color.WHITE);
reportss.setForeground(new java.awt.Color(0, 153, 153));
reportss.setOpaque(false);

editaccc.setBackground(Color.WHITE);
editaccc.setForeground(new java.awt.Color(0, 153, 153));
editaccc.setOpaque(false);

jDesktopPane1.removeAll();

   
    
    }//GEN-LAST:event_applcationMouseClicked

    private void applcationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applcationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_applcationMouseEntered

    private void applcationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applcationMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_applcationMouseExited

    private void myaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseExited

    }//GEN-LAST:event_myaccountMouseExited

    private void myaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseEntered

    }//GEN-LAST:event_myaccountMouseEntered

    private void myaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseClicked
      // current button
applcation.setOpaque(true);
applcation.setBackground(new java.awt.Color(0, 153, 153));
applcation.setForeground(Color.WHITE);

// other buttons
users.setBackground(Color.WHITE);
users.setForeground(new java.awt.Color(0, 153, 153));
users.setOpaque(false);

myaccount.setBackground(Color.WHITE);
myaccount.setForeground(new java.awt.Color(0, 153, 153));
myaccount.setOpaque(false);

reportss.setBackground(Color.WHITE);
reportss.setForeground(new java.awt.Color(0, 153, 153));
reportss.setOpaque(false);

editaccc.setBackground(Color.WHITE);
editaccc.setForeground(new java.awt.Color(0, 153, 153));
editaccc.setOpaque(false);

jDesktopPane1.removeAll();

    }//GEN-LAST:event_myaccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maindash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maindash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accname;
    private javax.swing.JLabel applcation;
    private javax.swing.JLabel editaccc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logout;
    public javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel myaccount;
    private javax.swing.JLabel reportss;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
