/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeinfo;

/**
 *
 * @author andre
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form addapplications
     */
    public Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        savebttn = new javax.swing.JLabel();
        clearr = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        select = new javax.swing.JLabel();
        partylist = new javax.swing.JComboBox<>();
        positionn = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidatestable = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        candidatestable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        mname1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        savebttn1 = new javax.swing.JLabel();
        clearr1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lname1 = new javax.swing.JLabel();
        fname1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cid1 = new javax.swing.JLabel();
        select1 = new javax.swing.JLabel();
        partylist1 = new javax.swing.JComboBox<>();
        positionn1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        age1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        candidatestable2 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setBorder(null);
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Firstname:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 20));

        mname.setForeground(new java.awt.Color(204, 0, 0));
        mname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 240, 20));

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("partylist");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 20));

        jPanel4.setLayout(null);

        image.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        image.setForeground(new java.awt.Color(153, 153, 153));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageMouseEntered(evt);
            }
        });
        jPanel4.add(image);
        image.setBounds(0, 0, 100, 100);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 100));

        jLabel26.setBackground(new java.awt.Color(255, 153, 102));
        jLabel26.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("  ADD APPLICATION");
        jLabel26.setOpaque(true);
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        savebttn.setBackground(new java.awt.Color(204, 0, 0));
        savebttn.setForeground(new java.awt.Color(255, 255, 255));
        savebttn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savebttn.setText("save");
        savebttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        savebttn.setOpaque(true);
        savebttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                savebttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                savebttnMouseExited(evt);
            }
        });
        jPanel2.add(savebttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 90, 20));

        clearr.setBackground(new java.awt.Color(204, 0, 0));
        clearr.setForeground(new java.awt.Color(255, 255, 255));
        clearr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clearr.setText("Clear all");
        clearr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        clearr.setOpaque(true);
        clearr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearrMouseClicked(evt);
            }
        });
        jPanel2.add(clearr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 90, 20));

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Lastname:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 20));

        lname.setForeground(new java.awt.Color(204, 0, 0));
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 240, 20));

        fname.setForeground(new java.awt.Color(204, 0, 0));
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 240, 20));

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("ID:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, 20));

        cid.setForeground(new java.awt.Color(204, 0, 0));
        cid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 20));

        select.setBackground(new java.awt.Color(204, 0, 0));
        select.setForeground(new java.awt.Color(255, 255, 255));
        select.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        select.setText("Select");
        select.setOpaque(true);
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectMouseClicked(evt);
            }
        });
        jPanel2.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 20));

        jPanel2.add(partylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 240, 20));

        jPanel2.add(positionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 240, 20));

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Position:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 20));

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Middlename:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 20));

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("age");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 20));

        age.setForeground(new java.awt.Color(204, 0, 0));
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, 20));

        jInternalFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 430));

        candidatestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        candidatestable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(candidatestable);

        jInternalFrame1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 380, 390));

        jLabel27.setBackground(new java.awt.Color(255, 153, 102));
        jLabel27.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" SELECT CANDIDATE");
        jLabel27.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 380, 40));

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 110, 35));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 35));

        candidatestable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        candidatestable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(candidatestable1);

        jInternalFrame1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 380, 390));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 270, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Firstname:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 20));

        mname1.setForeground(new java.awt.Color(204, 0, 0));
        mname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel5.add(mname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 240, 20));

        jLabel15.setText("partylist");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 20));

        jPanel7.setLayout(null);

        image1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        image1.setForeground(new java.awt.Color(153, 153, 153));
        image1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        image1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                image1MouseEntered(evt);
            }
        });
        jPanel7.add(image1);
        image1.setBounds(0, 0, 100, 100);

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 100));

        jLabel28.setBackground(new java.awt.Color(0, 204, 204));
        jLabel28.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("  ADD APPLICATION");
        jLabel28.setOpaque(true);
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        savebttn1.setBackground(new java.awt.Color(0, 153, 153));
        savebttn1.setForeground(new java.awt.Color(255, 255, 255));
        savebttn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savebttn1.setText("save");
        savebttn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        savebttn1.setOpaque(true);
        savebttn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebttn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                savebttn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                savebttn1MouseExited(evt);
            }
        });
        jPanel5.add(savebttn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 90, 20));

        clearr1.setBackground(new java.awt.Color(0, 153, 153));
        clearr1.setForeground(new java.awt.Color(255, 255, 255));
        clearr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clearr1.setText("Clear all");
        clearr1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        clearr1.setOpaque(true);
        clearr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearr1MouseClicked(evt);
            }
        });
        jPanel5.add(clearr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 90, 20));

        jLabel18.setText("Lastname:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 20));

        lname1.setForeground(new java.awt.Color(204, 0, 0));
        lname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel5.add(lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 240, 20));

        fname1.setForeground(new java.awt.Color(204, 0, 0));
        fname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel5.add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 240, 20));

        jLabel19.setText("ID:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 70, 20));

        cid1.setForeground(new java.awt.Color(204, 0, 0));
        cid1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel5.add(cid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 210, 20));

        select1.setBackground(new java.awt.Color(0, 153, 153));
        select1.setForeground(new java.awt.Color(255, 255, 255));
        select1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        select1.setText("Select");
        select1.setOpaque(true);
        select1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                select1MouseClicked(evt);
            }
        });
        jPanel5.add(select1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 20));

        jPanel5.add(partylist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 240, 20));

        jPanel5.add(positionn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 240, 20));

        jLabel20.setText("Position:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 20));

        jLabel21.setText("Middlename:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 20));

        jLabel22.setText("age");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 20));

        age1.setForeground(new java.awt.Color(204, 0, 0));
        age1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel5.add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, 20));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 430));

        candidatestable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        candidatestable2.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(candidatestable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 380, 390));

        jLabel29.setBackground(new java.awt.Color(0, 204, 204));
        jLabel29.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(" SELECT Applicants");
        jLabel29.setOpaque(true);
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 380, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 810, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked

    }//GEN-LAST:event_imageMouseClicked

    private void imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseEntered

    }//GEN-LAST:event_imageMouseEntered

    private void savebttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebttnMouseClicked

        String position = positionn.getSelectedItem().toString();

        if (getids()) {
            // Check if candidate's age is valid (between 16 and 59)
            if(cid.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No candidate selected yet!");
            }
            if (Age < 16 || Age >= 60) {
                JOptionPane.showMessageDialog(null, "Candidate must be between 16 and 59 years old.");
                return;
            }

            // Check if candidate is below 21 years old
            if (Age < 24) {
                if (!position.equals("SK chairman") && !position.equals("SK councilor")) {
                    JOptionPane.showMessageDialog(null, "Candidates aged 24 and below can only run as SK chairman or SK councilor.");
                } else {
                    addapplication();  // Valid case for SK chairman or SK councilor
                }
                return; // Exit after check
            }

            // Check if candidate is 21 or above
            if (Age >= 24) {
                if (position.equals("SK chairman") || position.equals("SK councilor")) {
                    JOptionPane.showMessageDialog(null, "Candidates aged 24 and above cannot run as SK chairman or SK councilor.");
                } else {
                    addapplication();  // Valid case for other positions
                }
            }
        }

    }//GEN-LAST:event_savebttnMouseClicked

    private void savebttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebttnMouseEntered
        savebttn.setBackground(Color.white);
        savebttn.setForeground(new java.awt.Color(204,0,0));
    }//GEN-LAST:event_savebttnMouseEntered

    private void savebttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebttnMouseExited

        savebttn.setBackground(new java.awt.Color(204,0,0));
        savebttn.setForeground(Color.white);
    }//GEN-LAST:event_savebttnMouseExited

    private void clearrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearrMouseClicked
        lname.setText("");
        lname.setText("");
        fname.setText("");
        cid.setText("");
        age.setText("");
        image.setIcon(null);
    }//GEN-LAST:event_clearrMouseClicked

    private void selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseClicked
        int rowIndex = candidatestable.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item!");
        } else {
            try {
                dbconnect dbc = new dbconnect();
                TableModel tbl = candidatestable.getModel();
                ResultSet rs = dbc.getData("SELECT * FROM candidates WHERE cid = '" + tbl.getValueAt(rowIndex, 0) + "'");

                if (rs.next()) {

                    cid.setText(""+rs.getInt("cid"));
                    fname.setText(""+rs.getString("lname"));
                    lname.setText(""+rs.getString("lname"));
                    mname.setText(""+rs.getString("mname"));
                    age.setText(""+rs.getString("age"));

                    image.setIcon(ResizeImage(rs.getString("cimage"),null,image));

                }

            } catch (SQLException ex) {
                System.out.println("" + ex);
            }
        }
    }//GEN-LAST:event_selectMouseClicked

    private void jInternalFrame1formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1formInternalFrameActivated
        loadPositions();
        loadPartylist();
    }//GEN-LAST:event_jInternalFrame1formInternalFrameActivated

    private void image1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1MouseClicked

    }//GEN-LAST:event_image1MouseClicked

    private void image1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1MouseEntered

    }//GEN-LAST:event_image1MouseEntered

    private void savebttn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebttn1MouseClicked

        String position = positionn.getSelectedItem().toString();

        if (getids()) {
            // Check if candidate's age is valid (between 16 and 59)
            if(cid.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No candidate selected yet!");
            }
            if (Age < 16 || Age >= 60) {
                JOptionPane.showMessageDialog(null, "Candidate must be between 16 and 59 years old.");
                return;
            }

            // Check if candidate is below 21 years old
            if (Age < 24) {
                if (!position.equals("SK chairman") && !position.equals("SK councilor")) {
                    JOptionPane.showMessageDialog(null, "Candidates aged 24 and below can only run as SK chairman or SK councilor.");
                } else {
                    addapplication();  // Valid case for SK chairman or SK councilor
                }
                return; // Exit after check
            }

            // Check if candidate is 21 or above
            if (Age >= 24) {
                if (position.equals("SK chairman") || position.equals("SK councilor")) {
                    JOptionPane.showMessageDialog(null, "Candidates aged 24 and above cannot run as SK chairman or SK councilor.");
                } else {
                    addapplication();  // Valid case for other positions
                }
            }
        }

    }//GEN-LAST:event_savebttn1MouseClicked

    private void savebttn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebttn1MouseEntered
        savebttn.setBackground(Color.white);
        savebttn.setForeground(new java.awt.Color(204,0,0));
    }//GEN-LAST:event_savebttn1MouseEntered

    private void savebttn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebttn1MouseExited

        savebttn.setBackground(new java.awt.Color(204,0,0));
        savebttn.setForeground(Color.white);
    }//GEN-LAST:event_savebttn1MouseExited

    private void clearr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearr1MouseClicked
        lname.setText("");
        lname.setText("");
        fname.setText("");
        cid.setText("");
        age.setText("");
        image.setIcon(null);
    }//GEN-LAST:event_clearr1MouseClicked

    private void select1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_select1MouseClicked
        int rowIndex = candidatestable.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item!");
        } else {
            try {
                dbconnect dbc = new dbconnect();
                TableModel tbl = candidatestable.getModel();
                ResultSet rs = dbc.getData("SELECT * FROM candidates WHERE cid = '" + tbl.getValueAt(rowIndex, 0) + "'");

                if (rs.next()) {

                    cid.setText(""+rs.getInt("cid"));
                    fname.setText(""+rs.getString("lname"));
                    lname.setText(""+rs.getString("lname"));
                    mname.setText(""+rs.getString("mname"));
                    age.setText(""+rs.getString("age"));

                    image.setIcon(ResizeImage(rs.getString("cimage"),null,image));

                }

            } catch (SQLException ex) {
                System.out.println("" + ex);
            }
        }
    }//GEN-LAST:event_select1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel age1;
    private javax.swing.JTable candidatestable;
    private javax.swing.JTable candidatestable1;
    private javax.swing.JTable candidatestable2;
    private javax.swing.JLabel cid;
    private javax.swing.JLabel cid1;
    private javax.swing.JLabel clearr;
    private javax.swing.JLabel clearr1;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel fname1;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lname1;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel mname1;
    private javax.swing.JComboBox<String> partylist;
    private javax.swing.JComboBox<String> partylist1;
    private javax.swing.JComboBox<String> positionn;
    private javax.swing.JComboBox<String> positionn1;
    private javax.swing.JLabel savebttn;
    private javax.swing.JLabel savebttn1;
    private javax.swing.JLabel select;
    private javax.swing.JLabel select1;
    // End of variables declaration//GEN-END:variables
}
