/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transactions;

import ADMINDASH.editoption;
import ADMINDASH.maindash;
import ESTRERA.loginform;
import config.Session;
import config.dbconnect;
import employeeinfo.Employees;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author II
 */
public class generatepayroll extends javax.swing.JFrame {

    /**
     * Creates new form generatepayroll
     */
    public generatepayroll() {
        setUndecorated(true);
        initComponents();
        loadEmployeesIntoCombo();
    }
public void loadEmployeesIntoCombo() {
    comboEmployees.removeAllItems();
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll_management", "root", "")) {
        String sql = "SELECT e.id, u.fname, u.lname FROM employees e JOIN users u ON e.uid = u.uid ORDER BY u.fname, u.lname";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            int employeeId = rs.getInt("id");  // employees.id is the PK
            String fname = rs.getString("fname");
            String lname = rs.getString("lname");
            String display = employeeId + " - " + fname + " " + lname;
            comboEmployees.addItem(display);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading employees: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        myaccount = new javax.swing.JLabel();
        reportss = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        accname = new javax.swing.JLabel();
        editaccc = new javax.swing.JLabel();
        applcation = new javax.swing.JLabel();
        Empreg = new javax.swing.JLabel();
        Empreg1 = new javax.swing.JLabel();
        Empreg2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtPhilhealthDeduction = new javax.swing.JTextField();
        txtPayPeriod = new javax.swing.JTextField();
        txtGrossSalary = new javax.swing.JTextField();
        txtSSSDeduction = new javax.swing.JTextField();
        btnAddPayroll = new javax.swing.JButton();
        txtPagibigDeduction = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPaymentDate = new javax.swing.JTextField();
        txtNetSalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboEmployees = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(153, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 25));

        minimize.setBackground(new java.awt.Color(153, 255, 204));
        minimize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        main.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 25));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("     ADMINISTRATORS DASHBOARD");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jLabel1.setOpaque(true);
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 810, 70));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 41, -1, -1));

        users.setBackground(new java.awt.Color(221, 21, 21));
        users.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        users.setForeground(new java.awt.Color(0, 153, 153));
        users.setText("  Users");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
        });
        sidebar.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));

        myaccount.setBackground(new java.awt.Color(255, 255, 255));
        myaccount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        myaccount.setForeground(new java.awt.Color(0, 153, 153));
        myaccount.setText("  My account");
        myaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myaccountMouseExited(evt);
            }
        });
        sidebar.add(myaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 40));

        reportss.setBackground(new java.awt.Color(204, 0, 0));
        reportss.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reportss.setForeground(new java.awt.Color(0, 153, 153));
        reportss.setText("  Reports");
        reportss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportssMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportssMouseExited(evt);
            }
        });
        sidebar.add(reportss, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 40));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 153, 153));
        logout.setText("  Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 160, 40));

        accname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Staff.png"))); // NOI18N
        sidebar.add(accname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        editaccc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editaccc.setForeground(new java.awt.Color(0, 153, 153));
        editaccc.setText("  Settings");
        editaccc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editacccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editacccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editacccMouseExited(evt);
            }
        });
        sidebar.add(editaccc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 40));

        applcation.setBackground(new java.awt.Color(204, 0, 0));
        applcation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        applcation.setForeground(new java.awt.Color(0, 153, 153));
        applcation.setText("My account");
        applcation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applcationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applcationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applcationMouseExited(evt);
            }
        });
        sidebar.add(applcation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        Empreg.setBackground(new java.awt.Color(204, 0, 0));
        Empreg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Empreg.setForeground(new java.awt.Color(0, 153, 153));
        Empreg.setText("View payroll");
        Empreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpregMouseExited(evt);
            }
        });
        sidebar.add(Empreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 40));

        Empreg1.setBackground(new java.awt.Color(255, 255, 255));
        Empreg1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Empreg1.setText("Employess");
        Empreg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Empreg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Empreg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Empreg1MouseExited(evt);
            }
        });
        sidebar.add(Empreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 40));

        Empreg2.setBackground(new java.awt.Color(204, 0, 0));
        Empreg2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Empreg2.setText("generate payroll");
        Empreg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Empreg2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Empreg2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Empreg2MouseExited(evt);
            }
        });
        sidebar.add(Empreg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 170, 40));

        main.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 170, 610));

        jPanel3.setBackground(new java.awt.Color(248, 248, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhilhealthDeduction.setEditable(false);
        jPanel3.add(txtPhilhealthDeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 290, 40));
        jPanel3.add(txtPayPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, 40));
        jPanel3.add(txtGrossSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 290, 40));

        txtSSSDeduction.setEditable(false);
        jPanel3.add(txtSSSDeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 290, 40));

        btnAddPayroll.setText("Generate Payroll");
        btnAddPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPayrollActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 200, 60));

        txtPagibigDeduction.setEditable(false);
        jPanel3.add(txtPagibigDeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 290, 40));

        jLabel2.setText("Payment Date:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel4.setText("Employee ID:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel6.setText("Pay Period:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel7.setText("Gross Salary:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel8.setText("SSS deduction:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel9.setText("PagIbig Deduction:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));
        jPanel3.add(txtPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 300, 40));

        txtNetSalary.setEditable(false);
        jPanel3.add(txtNetSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 300, 40));

        jLabel10.setText("PhilHealth deduction:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel11.setText("Net Salary:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jPanel3.add(comboEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 40));

        main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 780, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Session sess = Session.getInstance();
        dbconnect dbc = new dbconnect();
        String action = "User with ID "+sess.getId()+" logged out";
        dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" + +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");

        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited

    }//GEN-LAST:event_jLabel5MouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered

    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited

    }//GEN-LAST:event_minimizeMouseExited

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        maindash mm = new maindash();
        mm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_usersMouseClicked

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered

    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited

    }//GEN-LAST:event_usersMouseExited

    private void myaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseClicked

    }//GEN-LAST:event_myaccountMouseClicked

    private void myaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseEntered

    }//GEN-LAST:event_myaccountMouseEntered

    private void myaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myaccountMouseExited

    }//GEN-LAST:event_myaccountMouseExited

    private void reportssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportssMouseClicked

    }//GEN-LAST:event_reportssMouseClicked

    private void reportssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportssMouseEntered

    }//GEN-LAST:event_reportssMouseEntered

    private void reportssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportssMouseExited

    }//GEN-LAST:event_reportssMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dbconnect dbc = new dbconnect();
        Session sess= Session.getInstance();

        String action = "User with ID "+sess.getId()+" logged out";
        dbc.insertData("INSERT INTO logged(userid, action, date) VALUES ('" +sess.getId() + "', '" + action + "', '" + LocalDateTime.now() + "')");

        loginform lfm = new loginform();
        lfm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered

    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited

    }//GEN-LAST:event_logoutMouseExited

    private void editacccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseClicked
        editoption eo = new editoption();
        eo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editacccMouseClicked

    private void editacccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseEntered

    }//GEN-LAST:event_editacccMouseEntered

    private void editacccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editacccMouseExited

    }//GEN-LAST:event_editacccMouseExited

    private void applcationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applcationMouseClicked

    }//GEN-LAST:event_applcationMouseClicked

    private void applcationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applcationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_applcationMouseEntered

    private void applcationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applcationMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_applcationMouseExited

    private void EmpregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpregMouseClicked
        ViewPayroll vv = new ViewPayroll();
        vv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmpregMouseClicked

    private void EmpregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpregMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpregMouseEntered

    private void EmpregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpregMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpregMouseExited

    private void Empreg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Empreg1MouseClicked
       Employees e = new Employees();
       e.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Empreg1MouseClicked

    private void Empreg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Empreg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Empreg1MouseEntered

    private void Empreg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Empreg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Empreg1MouseExited

    private void Empreg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Empreg2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Empreg2MouseClicked

    private void Empreg2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Empreg2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Empreg2MouseEntered

    private void Empreg2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Empreg2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Empreg2MouseExited

    private void btnAddPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPayrollActionPerformed
      try {
        // Get selected employee from comboEmployee
        String selected = (String) comboEmployees.getSelectedItem();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select an employee.");
            return;
        }
        int employeeId = Integer.parseInt(selected.split(" - ")[0]); // extract employee.id

        // Get other inputs
        String payPeriod = txtPayPeriod.getText().trim();
        String grossSalaryStr = txtGrossSalary.getText().trim();
        String paymentDateStr = txtPaymentDate.getText().trim();

        if (payPeriod.isEmpty() || grossSalaryStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all required fields.");
            return;
        }

        double grossSalary = Double.parseDouble(grossSalaryStr);

        // Calculate deductions
        double sssDeduction = grossSalary * 0.045; // 4.5%
        double pagibigDeduction = Math.min(grossSalary * 0.01, 1500); // 1% or 1500 whichever is smaller
        double philhealthDeduction = 1500; // fixed amount example (adjust as needed)

        double totalDeductions = sssDeduction + pagibigDeduction + philhealthDeduction;
        double netSalary = grossSalary - totalDeductions;

        if (netSalary < 0) {
            JOptionPane.showMessageDialog(this, "Net Salary cannot be negative. Please check the gross salary.");
            return;
        }

        // Show calculated deductions and net salary in text fields
        txtSSSDeduction.setText(String.format("%.2f", sssDeduction));
        txtPagibigDeduction.setText(String.format("%.2f", pagibigDeduction));
        txtPhilhealthDeduction.setText(String.format("%.2f", philhealthDeduction));
        txtNetSalary.setText(String.format("%.2f", netSalary));

        // Parse or default payment date
        java.sql.Date paymentDate;
        if (paymentDateStr.isEmpty()) {
            paymentDate = new java.sql.Date(System.currentTimeMillis());
            txtPaymentDate.setText(paymentDate.toString());
        } else {
            paymentDate = java.sql.Date.valueOf(paymentDateStr); // expects yyyy-MM-dd format
        }

        // Insert into DB
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll_management", "root", "");
             PreparedStatement stmt = conn.prepareStatement(
                "INSERT INTO payroll (employee_id, pay_period, gross_salary, deductions, net_salary, payment_date) " +
                "VALUES (?, ?, ?, ?, ?, ?)")) {

            stmt.setInt(1, employeeId);
            stmt.setString(2, payPeriod);
            stmt.setDouble(3, grossSalary);
            stmt.setDouble(4, totalDeductions);
            stmt.setDouble(5, netSalary);
            stmt.setDate(6, paymentDate);

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Payroll added successfully!");
                generatepayroll gg = new generatepayroll();
                gg.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add payroll record.");
            }
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Payment Date must be in yyyy-MM-dd format.");
    }
    }//GEN-LAST:event_btnAddPayrollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generatepayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generatepayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generatepayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generatepayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generatepayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Empreg;
    private javax.swing.JLabel Empreg1;
    private javax.swing.JLabel Empreg2;
    private javax.swing.JLabel accname;
    private javax.swing.JLabel applcation;
    private javax.swing.JButton btnAddPayroll;
    private javax.swing.JComboBox<String> comboEmployees;
    private javax.swing.JLabel editaccc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logout;
    public javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel myaccount;
    private javax.swing.JLabel reportss;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField txtGrossSalary;
    private javax.swing.JTextField txtNetSalary;
    private javax.swing.JTextField txtPagibigDeduction;
    private javax.swing.JTextField txtPayPeriod;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtPhilhealthDeduction;
    private javax.swing.JTextField txtSSSDeduction;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
